# Generated by Django 2.1.5 on 2019-02-14 11:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_image', models.FileField(upload_to='uploads/')),
                ('job_description', models.TextField()),
                ('job_duties', models.TextField()),
                ('job_qualifications', models.TextField()),
                ('published_date', models.DateTimeField(default=datetime.datetime(2019, 2, 14, 11, 5, 14, 99221, tzinfo=utc))),
            ],
        ),
    ]
