# Generated by Django 2.1.5 on 2019-02-14 20:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='job_keywords',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_location',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 14, 20, 54, 56, 818613, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.ForeignKey(null=True, on_delete='models.CASCADE', to='hr.JobCategory'),
        ),
    ]
